locals {
  is_split_vm      = var.deployment_mode == "split_vm"
  is_split_managed = var.deployment_mode == "split_managed"
}

# ── split_vm: PostgreSQL on a dedicated Linode VM ────────────────────────────
# The DB Linode has both a public interface (SSH access from admin) and a VPC
# interface (PostgreSQL traffic from the app). The firewall blocks port 5432
# from all public IPs — only the VPC subnet CIDR can reach it.

resource "linode_stackscript" "postgres_bootstrap" {
  count       = local.is_split_vm ? 1 : 0
  label       = "${var.prefix}-postgres-bootstrap"
  description = "Install Docker CE and start PostgreSQL in a container"
  images      = ["linode/ubuntu24.04"]
  is_public   = false

  script = <<-'SCRIPT'
    #!/bin/bash
    set -euo pipefail

    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get upgrade -y
    apt-get install -y ca-certificates curl gnupg

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      | tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    systemctl enable docker
    systemctl start docker

    mkdir -p /opt/dmarc/pgdata
  SCRIPT
}

resource "linode_instance" "db" {
  count           = local.is_split_vm ? 1 : 0
  label           = "${var.prefix}-db"
  region          = var.region
  type            = var.db_instance_type
  image           = "linode/ubuntu24.04"
  authorized_keys = [trimspace(var.ssh_public_key)]
  firewall_id     = var.db_firewall_id
  stackscript_id  = linode_stackscript.postgres_bootstrap[0].id

  tags = [var.prefix, var.environment, "db"]

  # VPC interface first — app connects to DB over this private IP.
  interface {
    purpose   = "vpc"
    subnet_id = var.vpc_subnet_id
  }

  # Public interface for SSH admin access (firewalled to admin_cidr only).
  interface {
    purpose = "public"
  }
}

# ── split_managed: Linode Managed PostgreSQL ──────────────────────────────────
# Linode manages the PostgreSQL instance, automated backups, and failover.
# The password is auto-generated by Linode — retrieve with:
#   terraform output -raw db_password

resource "linode_database_postgresql" "main" {
  count        = local.is_split_managed ? 1 : 0
  label        = "${var.prefix}-db"
  region       = var.region
  engine_id    = var.db_engine
  type         = "g6-nanog-1"
  cluster_size = var.db_cluster_size

  # Allow the app Linode's public IP to connect.
  # Add additional IPs here if needed (e.g. your office IP for psql access).
  allow_list = compact([var.app_public_ip])
}