"""
IP address table for DMARC sample data generation.

AUTO-GENERATED by tests/build_ip_table.py — do not edit by hand.
Regenerate when provider IP ranges change (run quarterly or when enrichment stops matching):

    python tests/build_ip_table.py

IPv4 only. IPv6 is intentionally excluded: see docs/developer-guide.md for the
known limitation around IPv6 geo-enrichment coverage in GeoLite2-City.

Generated: 2026-05-04 18:53 UTC
"""
from __future__ import annotations

# Each entry: {"ip": str, "cidr": str | None, "source": str}
# geo_anomaly entries also include: "country", "country_name", "asn", "note"

PROVIDER_IPS: dict[str, list[dict]] = {
    "microsoft_365": [
        {"ip": "40.92.25.154", "cidr": '40.92.0.0/15', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "40.92.179.51", "cidr": '40.92.0.0/15', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "40.93.76.204", "cidr": '40.92.0.0/15', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "40.107.12.205", "cidr": '40.107.0.0/16', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "40.107.89.153", "cidr": '40.107.0.0/16', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "40.107.166.102", "cidr": '40.107.0.0/16', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.100.25.154", "cidr": '52.100.0.0/15', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.100.179.51", "cidr": '52.100.0.0/15', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.101.76.204", "cidr": '52.100.0.0/15', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.102.12.205", "cidr": '52.102.0.0/16', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.102.89.153", "cidr": '52.102.0.0/16', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.102.166.102", "cidr": '52.102.0.0/16', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.103.6.103", "cidr": '52.103.0.0/17', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.103.44.205", "cidr": '52.103.0.0/17', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "52.103.83.50", "cidr": '52.103.0.0/17', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "104.47.6.103", "cidr": '104.47.0.0/17', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "104.47.44.205", "cidr": '104.47.0.0/17', "source": 'spf.protection.outlook.com SPF'},
        {"ip": "104.47.83.50", "cidr": '104.47.0.0/17', "source": 'spf.protection.outlook.com SPF'},
    ],
    "google_workspace": [
        {"ip": "74.125.12.205", "cidr": '74.125.0.0/16', "source": '_spf.google.com SPF'},
        {"ip": "74.125.89.153", "cidr": '74.125.0.0/16', "source": '_spf.google.com SPF'},
        {"ip": "74.125.166.102", "cidr": '74.125.0.0/16', "source": '_spf.google.com SPF'},
        {"ip": "209.85.134.103", "cidr": '209.85.128.0/17', "source": '_spf.google.com SPF'},
        {"ip": "209.85.172.205", "cidr": '209.85.128.0/17', "source": '_spf.google.com SPF'},
        {"ip": "209.85.211.50", "cidr": '209.85.128.0/17', "source": '_spf.google.com SPF'},
    ],
    "amazon_ses": [
        {"ip": "199.255.192.52", "cidr": '199.255.192.0/22', "source": 'amazonses.com SPF'},
        {"ip": "199.255.193.102", "cidr": '199.255.192.0/22', "source": 'amazonses.com SPF'},
        {"ip": "199.255.194.153", "cidr": '199.255.192.0/22', "source": 'amazonses.com SPF'},
        {"ip": "199.127.232.52", "cidr": '199.127.232.0/22', "source": 'amazonses.com SPF'},
        {"ip": "199.127.233.102", "cidr": '199.127.232.0/22', "source": 'amazonses.com SPF'},
        {"ip": "199.127.234.153", "cidr": '199.127.232.0/22', "source": 'amazonses.com SPF'},
        {"ip": "54.240.3.52", "cidr": '54.240.0.0/18', "source": 'amazonses.com SPF'},
        {"ip": "54.240.22.102", "cidr": '54.240.0.0/18', "source": 'amazonses.com SPF'},
        {"ip": "54.240.41.153", "cidr": '54.240.0.0/18', "source": 'amazonses.com SPF'},
        {"ip": "69.169.224.205", "cidr": '69.169.224.0/20', "source": 'amazonses.com SPF'},
        {"ip": "69.169.229.153", "cidr": '69.169.224.0/20', "source": 'amazonses.com SPF'},
        {"ip": "69.169.234.102", "cidr": '69.169.224.0/20', "source": 'amazonses.com SPF'},
        {"ip": "23.249.208.205", "cidr": '23.249.208.0/20', "source": 'amazonses.com SPF'},
        {"ip": "23.249.213.153", "cidr": '23.249.208.0/20', "source": 'amazonses.com SPF'},
        {"ip": "23.249.218.102", "cidr": '23.249.208.0/20', "source": 'amazonses.com SPF'},
        {"ip": "23.251.225.154", "cidr": '23.251.224.0/19', "source": 'amazonses.com SPF'},
        {"ip": "23.251.235.51", "cidr": '23.251.224.0/19', "source": 'amazonses.com SPF'},
        {"ip": "23.251.244.204", "cidr": '23.251.224.0/19', "source": 'amazonses.com SPF'},
        {"ip": "76.223.176.205", "cidr": '76.223.176.0/20', "source": 'amazonses.com SPF'},
        {"ip": "76.223.181.153", "cidr": '76.223.176.0/20', "source": 'amazonses.com SPF'},
        {"ip": "76.223.186.102", "cidr": '76.223.176.0/20', "source": 'amazonses.com SPF'},
        {"ip": "54.240.67.52", "cidr": '54.240.64.0/18', "source": 'amazonses.com SPF'},
        {"ip": "54.240.86.102", "cidr": '54.240.64.0/18', "source": 'amazonses.com SPF'},
        {"ip": "54.240.105.153", "cidr": '54.240.64.0/18', "source": 'amazonses.com SPF'},
        {"ip": "76.223.129.154", "cidr": '76.223.128.0/19', "source": 'amazonses.com SPF'},
        {"ip": "76.223.139.51", "cidr": '76.223.128.0/19', "source": 'amazonses.com SPF'},
        {"ip": "76.223.148.204", "cidr": '76.223.128.0/19', "source": 'amazonses.com SPF'},
        {"ip": "216.221.161.154", "cidr": '216.221.160.0/19', "source": 'amazonses.com SPF'},
        {"ip": "216.221.171.51", "cidr": '216.221.160.0/19', "source": 'amazonses.com SPF'},
        {"ip": "216.221.180.204", "cidr": '216.221.160.0/19', "source": 'amazonses.com SPF'},
        {"ip": "206.55.144.205", "cidr": '206.55.144.0/20', "source": 'amazonses.com SPF'},
        {"ip": "206.55.149.153", "cidr": '206.55.144.0/20', "source": 'amazonses.com SPF'},
        {"ip": "206.55.154.102", "cidr": '206.55.144.0/20', "source": 'amazonses.com SPF'},
        {"ip": "24.110.67.52", "cidr": '24.110.64.0/18', "source": 'amazonses.com SPF'},
        {"ip": "24.110.86.102", "cidr": '24.110.64.0/18', "source": 'amazonses.com SPF'},
        {"ip": "24.110.105.153", "cidr": '24.110.64.0/18', "source": 'amazonses.com SPF'},
    ],
    "yahoo": [
        {"ip": "67.195.228.110", "cidr": None, "source": 'mta5.am0.yahoodns.net (MX of yahoo.com)'},
        {"ip": "67.195.228.111", "cidr": None, "source": 'mta5.am0.yahoodns.net (MX of yahoo.com)'},
        {"ip": "98.136.96.74", "cidr": None, "source": 'mta5.am0.yahoodns.net (MX of yahoo.com)'},
        {"ip": "98.136.96.91", "cidr": None, "source": 'mta5.am0.yahoodns.net (MX of yahoo.com)'},
    ],
    "proofpoint": [
        {"ip": "148.163.130.170", "cidr": '148.163.0.0/16', "source": 'Proofpoint documented range'},
        {"ip": "148.163.7.43", "cidr": '148.163.0.0/16', "source": 'Proofpoint documented range'},
        {"ip": "148.163.200.19", "cidr": '148.163.0.0/16', "source": 'Proofpoint documented range'},
    ],
    "geo_anomaly": [
        {"ip": "5.44.42.1", "country": 'RU', "country_name": 'Russia', "asn": 'AS41805', "note": 'IQ-NET LLC, publicly routed Russian address block'},
        {"ip": "175.45.176.5", "country": 'KP', "country_name": 'North Korea', "asn": 'AS131279', "note": 'Star JV (state ISP), one of the few DPRK-assigned IPv4 ranges (175.45.176.0/22)'},
        {"ip": "31.2.128.1", "country": 'IR', "country_name": 'Iran', "asn": 'AS48159', "note": 'Telecommunications Company of Iran (TCI/Aria Shatel), 31.2.0.0/18'},
        {"ip": "178.172.160.1", "country": 'BY', "country_name": 'Belarus', "asn": 'AS6697', "note": 'Beltelecom (Belarusian state telecoms provider), 178.172.128.0/18'},
    ],
}
